### ISSUE TITLE
TODO list :3

### ISSUE THREAD

**Issue by rickycorte** [rickycorte/HikariBackend#1]
- [ ] Connection timeout
- [x] Create basic API "page" class
- [x] Add Path (URL) redirector to API pages
- [ ] Add worker child processes based on cpu cores
- [ ] Add custom master token to use as base optional API auth
- [ ] Use a fast logging library
- [ ] Measure Processing time and track responce codes

I think this is more than enouth for a !good project like this :cry:

Maybe one this this will be good... but who knows

**Comment by rickycorte** [comment]
https://github.com/rickycorte/HikariBackend/commit/6edaa6aec8206c446fa4308d3c7c6d3a97326910 adds api pages and dispatcher
